# Generated by Django 5.0.3 on 2024-03-27 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "regid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("phoneNo", models.CharField(max_length=15)),
                ("addressDetails", models.JSONField()),
                ("workExperience", models.JSONField()),
                ("qualifications", models.JSONField()),
                ("projects", models.JSONField()),
                ("photo", models.TextField()),
            ],
        ),
    ]
